Feature/issue 190 rearchitecture nomura
junjun-1345/aizuchi_app pull request #191
Opened 2024-07-05 07:02 UTC by tomoki-miso

## リアーキテクチャ(プロフィール取得） #190 

### コード修正点・追加点

-　MVVM+Repositoryの形でプロフィール表示画面の作成

### Q&A

### スクリーンショット
![Simulator Screen Recording - iPhone 15 - 2024-07-05 at 16 01 36](https://github.com/junjun-1345/aizuchi_app/assets/107928941/df8b5413-744d-410f-ab01-0a99f195a1eb)

2024-07-07 10:01 UTC, junjun-1345 requested changes

2024-07-07 10:01 UTC, junjun-1345 commented on lib/rearchitecture/feature/profile/state.dart
これって、ここで保持しているわけではなくて、データ構造のためのコードっていう認識でいけてる???

2024-07-07 10:01 UTC, junjun-1345 commented on lib/rearchitecture/feature/profile/view_model.dart
ここって、keep aliveじゃなくてもいい??
チャット画面とかやといちいち大規模なデータの取得が行われそうなんだが、、、、

2024-07-08 13:16 UTC, tomoki-miso commented on lib/rearchitecture/feature/profile/components/profile_tile.dart
特に理由はないのですが、強いて言うならばFlutterのListTileを参考にしているイメージです
https://api.flutter.dev/flutter/material/ListTile-class.html

2024-07-08 13:18 UTC, tomoki-miso commented on lib/rearchitecture/feature/profile/page.dart
> +          log(error.toString());
エラー出たとき用のやつです。
Printと同じ挙動ですが、リリースビルドで見れないのとリントに怒られないため採用してます
https://zenn.dev/fastriver/articles/flutter-debug-print

2024-07-08 13:19 UTC, tomoki-miso commented on lib/rearchitecture/feature/profile/state.dart
あってます！

2024-07-08 13:26 UTC, tomoki-miso commented on lib/rearchitecture/feature/profile/view_model.dart
逆にKeepAliveじゃない場合の方が毎回データ取得する気がします
https://qiita.com/haru-qiita/items/b7c60747874850beda5b#refkeepalive

2024-07-17 09:03 UTC, junjun-1345 approved these changes

2024-07-17 09:04 UTC, merged